### ISSUE TITLE
Sketch creator error

### ISSUE THREAD

**Issue by poqudrof** [ruby-processing/JRubyArt#18]
Hello, 

I have some trouble with the sketch creators. I have two kind of errors, here is the first kind : 

``` bash
[jiii@jeremy-alienware contributed]$ k9 create fred 200 200     
ArgumentError: wrong number of arguments (0 for 1)
   create! at /home/jiii/.rvm/gems/jruby-9.0.1.0/gems/jruby_art-1.1.2/lib/jruby_art/creators/creator.rb:198
    create at /home/jiii/.rvm/gems/jruby-9.0.1.0/gems/jruby_art-1.1.2/lib/jruby_art/runner.rb:101
  execute! at /home/jiii/.rvm/gems/jruby-9.0.1.0/gems/jruby_art-1.1.2/lib/jruby_art/runner.rb:72
   execute at /home/jiii/.rvm/gems/jruby-9.0.1.0/gems/jruby_art-1.1.2/lib/jruby_art/runner.rb:63
     <top> at /home/jiii/.rvm/gems/jruby-9.0.1.0/gems/jruby_art-1.1.2/bin/k9:10
      load at org/jruby/RubyKernel.java:957
    <eval> at /home/jiii/.rvm/gems/jruby-9.0.1.0/bin/k9:1
      eval at org/jruby/RubyKernel.java:978
     <top> at /home/jiii/.rvm/gems/jruby-9.0.1.0/bin/jruby_executable_hooks:15
```

I also had this other error, which was before I did the `k9 setup install` : 

``` 
NameError: undefined local variable or method `underscore' for "fred":String
  titleize at /home/jiii/.rvm/gems/jruby-9.1.2.0/gems/jruby_art-1.1.2/lib/jruby_art/helpers/string_extra.rb:6
   create! at /home/jiii/.rvm/gems/jruby-9.1.2.0/gems/jruby_art-1.1.2/lib/jruby_art/creators/creator.rb:200
    create at /home/jiii/.rvm/gems/jruby-9.1.2.0/gems/jruby_art-1.1.2/lib/jruby_art/runner.rb:101
  execute! at /home/jiii/.rvm/gems/jruby-9.1.2.0/gems/jruby_art-1.1.2/lib/jruby_art/runner.rb:72
   execute at /home/jiii/.rvm/gems/jruby-9.1.2.0/gems/jruby_art-1.1.2/lib/jruby_art/runner.rb:63
     <top> at /home/jiii/.rvm/gems/jruby-9.1.2.0/gems/jruby_art-1.1.2/bin/k9:10
      load at org/jruby/RubyKernel.java:962
    <eval> at /home/jiii/.rvm/gems/jruby-9.1.2.0/bin/k9:1
      eval at org/jruby/RubyKernel.java:983
     <top> at /home/jiii/.rvm/gems/jruby-9.1.2.0/bin/jruby_executable_hooks:15

```

### Environment

The other elements work well. 
 
```
JRubyArt version 1.1.2
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)
```

**Comment by monkstone** [comment]
@poqudrof it seems as though jruby has only just implemented refinements (so in version 9.0.1.0 probably did not exist) in my pure jruby environment (I don't use rvm) seems to work OK with jruby 9.1.2.0. I usually run in hybrid situation ie creation etc using MRI ruby and call jruby directly when firing up sketch. But I probably made change too early so I will reverse it. I've been a bit distracted by sonic-pi recently which is excellent and can probably interoperate with JRubyArt to produce sound light shows. And there is this [weird japanese thing](https://github.com/kn1kn1/haskap-jam-pack) that uses sonic-pi to create/control ruby -processing sketches (pretty experimental but I got it to work on Linux Mint).

**Comment by monkstone** [comment]
@poqudrof please test latest release, if fixed you can close issue.

**Comment by poqudrof** [comment]
Perfect it works again !
